# Generated by Django 3.0.8 on 2020-11-07 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20201107_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitude',
            name='category',
            field=models.ForeignKey(default='Quants', on_delete=django.db.models.deletion.CASCADE, related_name='categoryname1', to='coding.Categories', to_field='category_name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 7, 22, 13, 12, 781916)),
        ),
        migrations.AlterField(
            model_name='anwsers',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 7, 22, 13, 12, 777926)),
        ),
        migrations.AlterField(
            model_name='aptitude',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 7, 22, 13, 12, 783911)),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 7, 22, 13, 12, 768951)),
        ),
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 7, 22, 13, 12, 783911)),
        ),
    ]
