# Generated by Django 3.0.8 on 2020-12-22 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0016_auto_20201222_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 22, 9, 31, 22, 529465)),
        ),
        migrations.AlterField(
            model_name='anwsers',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 22, 9, 31, 22, 521439)),
        ),
        migrations.AlterField(
            model_name='aptitude',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 22, 9, 31, 22, 529465)),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 22, 9, 31, 22, 512276)),
        ),
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 22, 9, 31, 22, 529465)),
        ),
    ]
