# Generated by Django 3.0.8 on 2021-01-02 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0020_auto_20210102_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 2, 18, 47, 39, 214854)),
        ),
        migrations.AlterField(
            model_name='anwsers',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 2, 18, 47, 39, 208870)),
        ),
        migrations.AlterField(
            model_name='aptitude',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 2, 18, 47, 39, 217846)),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 2, 18, 47, 39, 196902)),
        ),
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 2, 18, 47, 39, 218843)),
        ),
        migrations.AlterUniqueTogether(
            name='job_search',
            unique_together={('title', 'location')},
        ),
    ]
