# Generated by Django 3.0.8 on 2020-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='desciption',
            field=models.TextField(blank=True),
        ),
    ]
