# Generated by Django 3.0.8 on 2020-11-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_desciption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='desciption',
        ),
    ]
