# Generated by Django 3.0.8 on 2020-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_auto_20201215_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='template',
            field=models.TextField(blank=True),
        ),
    ]
