# Generated by Django 3.0.8 on 2020-12-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_auto_20201215_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='code',
        ),
        migrations.RemoveField(
            model_name='playground',
            name='lang',
        ),
        migrations.CreateModel(
            name='ExtendPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_ins', to='compiler.PlayGround')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_lang', to='compiler.Language', to_field='lang')),
            ],
        ),
    ]
