# Generated by Django 3.0.8 on 2020-12-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('lock', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_names', to='coding.Company', to_field='company_name')),
                ('pattern', models.ManyToManyField(blank=True, related_name='categories_name', to='coding.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_name', to='authority.Mock', to_field='title')),
                ('questions', models.ManyToManyField(blank=True, related_name='question_series', to='coding.Aptitude')),
            ],
        ),
    ]
