# Generated by Django 3.0.8 on 2020-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_series',
            name='time_duration',
            field=models.IntegerField(default=90),
        ),
    ]
