# Generated by Django 3.0.8 on 2020-12-08 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0002_test_series_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='subscribers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribers_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_series',
            name='subscribers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribers_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Test_Given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_test', to='authority.Test_Series', to_field='title')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
