# Generated by Django 3.0.8 on 2020-12-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_auto_20201208_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_given',
            name='solution',
            field=models.CharField(default='[]', max_length=5000),
        ),
    ]
