# Generated by Django 3.0.8 on 2020-12-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_test_given_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_given',
            name='solution',
            field=models.CharField(default='{}', max_length=5000),
        ),
    ]
