# Generated by Django 3.0.8 on 2020-12-18 08:39

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compiler', '0005_auto_20201216_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('solution', ckeditor.fields.RichTextField(blank=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], default='Easy', max_length=100)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('Solved', 'Solved'), ('Attempted', 'Attempted')], default='Todo', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Programming_Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=1000)),
                ('question', models.ManyToManyField(related_name='todo_question', to='competitive.Programming')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Anwser', 'Wrong Anwser'), ('Runtime Error', 'Runtime Error')], max_length=1000)),
                ('runtime', models.IntegerField(default=0)),
                ('time', models.DateField(default=datetime.datetime.now)),
                ('solution', models.TextField(default='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_lang', to='compiler.Language', to_field='lang')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_question', to='competitive.Programming', to_field='title')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='programming',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_company', to='competitive.Programming_Companies', to_field='company_name'),
        ),
        migrations.AddField(
            model_name='programming',
            name='dislike',
            field=models.ManyToManyField(blank=True, default=None, related_name='program_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programming',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='program_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
