# Generated by Django 3.0.8 on 2020-12-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0002_programming_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='category',
            field=models.ForeignKey(default='Arrays', on_delete=django.db.models.deletion.CASCADE, related_name='program_category', to='competitive.Programming_Category', to_field='category_name'),
        ),
    ]
