# Generated by Django 3.0.8 on 2020-12-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0004_code_snippet_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_snippet',
            name='program',
            field=models.ForeignKey(default='Longest Palindromic Substring', on_delete=django.db.models.deletion.CASCADE, related_name='code_sol', to='competitive.Programming', to_field='title'),
        ),
    ]
