# Generated by Django 3.0.8 on 2020-12-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0005_code_snippet_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programming',
            name='company',
        ),
        migrations.AddField(
            model_name='programming',
            name='company',
            field=models.ManyToManyField(blank=True, default=None, related_name='program_company', to='competitive.Programming_Companies'),
        ),
        migrations.RemoveField(
            model_name='programming',
            name='tags',
        ),
        migrations.AddField(
            model_name='programming',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='program_tags', to='competitive.Programming_Category'),
        ),
    ]
