# Generated by Django 3.0.8 on 2020-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0006_auto_20201222_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='video',
            field=models.CharField(choices=[('Has Solution', 'Has Solution'), ('No Solution', 'No Solution')], default='No Solution', max_length=1000),
        ),
        migrations.AlterField(
            model_name='code_snippet',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
