# Generated by Django 3.0.8 on 2020-12-23 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_auto_20201216_1102'),
        ('competitive', '0007_auto_20201222_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='video',
            field=models.CharField(choices=[('Has solution', 'Has solution'), ('Has video solution', 'Has video solution')], default='Has solution', max_length=1000),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.TextField()),
                ('sol_cases', models.TextField()),
                ('public_cases', models.TextField()),
                ('public_sol_cases', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_ques', to='competitive.Programming', to_field='title')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temlate_ques', to='competitive.Programming', to_field='title')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_lang_name', to='compiler.Language', to_field='lang')),
            ],
        ),
    ]
