# Generated by Django 3.0.8 on 2020-12-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0008_auto_20201223_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
