# Generated by Django 3.0.8 on 2020-12-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0010_templates_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='question',
            field=models.ManyToManyField(blank=True, default=None, related_name='todo_question', to='competitive.Programming'),
        ),
    ]
